CFLAGS=-Wall -I../lib/uthash-1.9.3/src -std=gnu99 -pthread -g

all: mtn-server mtn-client

COMMON_SRC=mtn-common.c mtn-config.c mtn-protocol.c array_heap.c
SERVER_SRC=$(wildcard mtn-server*.c)
CLIENT_SRC=$(wildcard mtn-client*.c)

COMMON_OBJ=$(patsubst %.c, %.o, $(COMMON_SRC))
SERVER_OBJ=$(patsubst %.c, %.o, $(SERVER_SRC))
CLIENT_OBJ=$(patsubst %.c, %.o, $(CLIENT_SRC))

mtn-server: $(SERVER_OBJ) $(COMMON_OBJ)
	$(CC) $(CFLAGS) -o $@ $(SERVER_OBJ) $(COMMON_OBJ)

mtn-client: $(CLIENT_OBJ) $(COMMON_OBJ)
	$(CC) $(CFLAGS) -o $@ $(CLIENT_OBJ) $(COMMON_OBJ)

depend:
	makedepend -Y./ -- $(CFLAGS) -- $(COMMON_SRC) $(CLIENT_SRC) $(SERVER_SRC) >& /dev/null

clean:
	rm *.o

# DO NOT DELETE

mtn-common.o: mtn-common.h mtn-protocol.h ../lib/uthash-1.9.3/src/uthash.h
mtn-common.o: mtn-config.h
mtn-config.o: mtn-config.h ../lib/uthash-1.9.3/src/uthash.h mtn-common.h
mtn-config.o: mtn-protocol.h
mtn-protocol.o: mtn-protocol.h mtn-common.h ../lib/uthash-1.9.3/src/uthash.h
array_heap.o: array_heap.h ../lib/uthash-1.9.3/src/utarray.h
mtn-client.o: mtn-common.h mtn-protocol.h ../lib/uthash-1.9.3/src/uthash.h
mtn-client.o: mtn-client.h mtn-client-config.h mtn-config.h
mtn-client.o: mtn-client-server-list.h mtn-client-receiver.h
mtn-client.o: mtn-client-updater.h
mtn-client-config.o: mtn-client-config.h mtn-config.h
mtn-client-config.o: ../lib/uthash-1.9.3/src/uthash.h mtn-common.h
mtn-client-config.o: mtn-protocol.h
mtn-client-receiver.o: mtn-client-receiver.h mtn-client.h mtn-client-config.h
mtn-client-receiver.o: mtn-config.h ../lib/uthash-1.9.3/src/uthash.h
mtn-client-receiver.o: mtn-client-request.h mtn-client-server-list.h
mtn-client-receiver.o: mtn-common.h mtn-protocol.h
mtn-client-request.o: mtn-client-request.h mtn-client-server-list.h
mtn-client-request.o: ../lib/uthash-1.9.3/src/uthash.h mtn-common.h
mtn-client-request.o: mtn-protocol.h mtn-client.h mtn-client-config.h
mtn-client-request.o: mtn-config.h
mtn-client-server-list.o: mtn-client-server-list.h
mtn-client-server-list.o: ../lib/uthash-1.9.3/src/uthash.h mtn-common.h
mtn-client-server-list.o: mtn-protocol.h mtn-client.h mtn-client-config.h
mtn-client-server-list.o: mtn-config.h
mtn-client-updater.o: mtn-client-updater.h mtn-client-server-list.h
mtn-client-updater.o: ../lib/uthash-1.9.3/src/uthash.h mtn-common.h
mtn-client-updater.o: mtn-protocol.h array_heap.h
mtn-client-updater.o: ../lib/uthash-1.9.3/src/utarray.h mtn-client.h
mtn-client-updater.o: mtn-client-config.h mtn-config.h mtn-client-request.h
mtn-server.o: mtn-common.h mtn-protocol.h ../lib/uthash-1.9.3/src/uthash.h
mtn-server.o: mtn-server.h mtn-server-config.h mtn-config.h
mtn-server.o: mtn-server-receiver.h mtn-server-client-list.h
mtn-server.o: mtn-server-transmitter.h
mtn-server-client-list.o: mtn-server-client-list.h
mtn-server-client-list.o: ../lib/uthash-1.9.3/src/uthash.h
mtn-server-config.o: mtn-server-config.h mtn-config.h
mtn-server-config.o: ../lib/uthash-1.9.3/src/uthash.h mtn-common.h
mtn-server-config.o: mtn-protocol.h
mtn-server-data-message.o: mtn-server-data-message.h mtn-config.h
mtn-server-data-message.o: ../lib/uthash-1.9.3/src/uthash.h
mtn-server-receiver.o: mtn-server-receiver.h mtn-protocol.h
mtn-server-receiver.o: mtn-server-client-list.h
mtn-server-receiver.o: ../lib/uthash-1.9.3/src/uthash.h mtn-common.h
mtn-server-receiver.o: mtn-server.h mtn-server-config.h mtn-config.h
